spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/behoo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: test
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8889

shiro-redis:
  enable: true
  redis-manager:
    host: 127.0.0.1:6379

demo:
  jwt:
    #加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token 过期时间
    expire: 604800
    header: Authorization

mail:
  host: smtp.qq.com
  port: 465
  debug: false
  username: 2775153204@qq.com
  password: kbarsotujpvjddfg
  default-encoding: utf-8
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

